#!/usr/bin/env python3
"""Validate and render the frozen adoption-baseline snapshot."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import tomllib

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = REPO_ROOT / "adoption-baseline.toml"
EXPECTED_PACKAGES = {
    "pdfplumber",
    "pdfplumber-core",
    "pdfplumber-parse",
    "pdfplumber-cli",
    "pdfplumber-rs",
    "pdfplumber-wasm",
}
PINNED_GITHUB_URL = re.compile(r"^https://github\.com/[^/]+/[^/]+/blob/[0-9a-f]{40}/")


class BaselineError(ValueError):
    """Raised when the frozen source violates its public contract."""


def require(condition: bool, message: str) -> None:
    if not condition:
        raise BaselineError(message)


def load_source() -> dict[str, object]:
    try:
        return tomllib.loads(SOURCE_PATH.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as error:
        raise BaselineError(f"cannot read {SOURCE_PATH.name}: {error}") from error


def validate(data: dict[str, object]) -> None:
    require(data.get("schema_version") == 1, "schema_version must be 1")
    require(data.get("snapshot_date") == "2026-08-26", "unexpected snapshot_date")
    require(data.get("release_version") == "0.3.0", "unexpected release_version")

    packages = data.get("registry_packages")
    require(isinstance(packages, list), "registry_packages must be an array")
    package_names = [row.get("package") for row in packages if isinstance(row, dict)]
    require(set(package_names) == EXPECTED_PACKAGES, "registry package set is incomplete")
    require(len(package_names) == len(set(package_names)), "registry packages must be unique")
    for row in packages:
        require(isinstance(row, dict), "registry package rows must be tables")
        require(str(row.get("source_url", "")).startswith("https://"), "package source must be HTTPS")
        require(bool(row.get("limitations")), "every package needs limitations")

    dependents = data.get("dependent_repositories")
    require(isinstance(dependents, dict), "dependent_repositories must be a table")
    entries = dependents.get("entries", [])
    require(dependents.get("observed_count") == len(entries) == 3, "dependent count mismatch")
    for entry in entries:
        require(PINNED_GITHUB_URL.match(entry.get("manifest_url", "")) is not None, "dependent manifest must pin a Git SHA")

    visits = data.get("documentation_visits")
    require(isinstance(visits, dict), "documentation_visits must be a table")
    require(visits.get("window_start") == "2026-08-12", "unexpected traffic start")
    require(visits.get("window_end") == "2026-08-25", "unexpected traffic end")

    issues = data.get("issues")
    require(isinstance(issues, dict), "issues must be a table")
    require(issues.get("open", 0) + issues.get("closed", 0) == issues.get("total"), "issue totals disagree")

    targets = data.get("targets")
    require(isinstance(targets, dict), "targets must be a table")
    require(targets.get("quarterly_growth_targets_defined") is False, "growth targets must remain unset")


def escaped(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def source_link(url: str, label: str = "source") -> str:
    return f"[{label}]({url})"


def render(data: dict[str, object]) -> str:
    packages = data["registry_packages"]
    dependents = data["dependent_repositories"]
    visits = data["documentation_visits"]
    activation = data["activation_failures"]
    issues = data["issues"]
    adopters = data["external_adopters"]
    targets = data["targets"]

    lines = [
        "# Adoption baseline — 2026-08-26",
        "",
        "<!-- Generated by scripts/generate_adoption_baseline.py from adoption-baseline.toml. Do not edit directly. -->",
        "",
        f"Observed at `{data['observed_at_utc']}` for release `{data['release_version']}`. This is a frozen observation, not a live dashboard and not a growth target.",
        "",
        "## Registry downloads",
        "",
        "Registry downloads are not people or adopters. They can include Continuous Integration, mirrors, caches, bots, and repeated installation by the same user. Do not sum the Rust package counters: `pdfplumber-core` and `pdfplumber-parse` are normally fetched transitively with higher-level crates.",
        "",
        "| Package | Ecosystem | Frozen observation | Source |",
        "|---|---|---|---|",
    ]
    for row in packages:
        if row["ecosystem"] == "crates.io":
            observation = (
                f"all-time {row['downloads_all_time']}; registry-recent {row['downloads_recent']}; "
                f"release {row['release_version']} {row['downloads_release']}"
            )
        else:
            observation = (
                f"{row['downloads_window']} from {row['window_start']} through {row['window_end']}"
            )
        lines.append(
            f"| `{escaped(row['package'])}` | {escaped(row['ecosystem'])} | {escaped(observation)} | {source_link(row['source_url'])} |"
        )
    lines.extend(
        [
            "",
            "The PyPI figure is a secondary BigQuery proxy over the official public download dataset, excludes mirrors, and uses the fixed release-through-last-complete-day window. PyPI's ordinary project JSON returned `-1` placeholders rather than usable download counts. The npm figure uses a fixed seven-day registry-API window. Every row's source-specific limitations remain in `adoption-baseline.toml`.",
            "",
            "## Public dependent repositories",
            "",
            "GitHub public-code search is a lower bound because indexing can lag or omit private and unindexed repositories. A declared manifest dependency also does not prove active or production use.",
            "",
            "| Repository | Surface | Pinned manifest observation |",
            "|---|---|---|",
        ]
    )
    for entry in dependents["entries"]:
        lines.append(
            f"| `{escaped(entry['repository'])}` | {escaped(entry['surface'])} | [{escaped(entry['requirement'])}]({entry['manifest_url']}) |"
        )
    lines.extend(
        [
            "",
            f"The [public-code query]({dependents['search_source_url']}) found {dependents['observed_count']} canonical package manifests. crates.io reverse-dependency queries reported {dependents['crates_io_external_count']} external published dependencies after excluding this repository's own packages, and the exact Python distribution-name manifest search found {dependents['python_manifest_count']} external repositories.",
            "",
            "## Documentation visits",
            "",
            f"GitHub's authenticated, push-access-only [repository traffic]({visits['views_source_url']}) endpoint reported {visits['views']} views from {visits['unique_visitors']} unique visitors for `{visits['window_start']}` through `{visits['window_end']}`. The [popular-path response]({visits['paths_source_url']}) reported {visits['overview_views']} views/{visits['overview_uniques']} uniques for the Overview path, which renders the README, and {visits['readme_views']} view/{visits['readme_uniques']} unique for the direct `README.md` path. These paths can overlap and are not summed.",
            "",
            f"GitHub exposes only the top 10 paths for this 14-day window. `{visits['docs_paths_in_top_ten']}` `docs/*` paths appeared there; that does not mean zero documentation visits.",
            "",
            "## Activation failures and issues",
            "",
            f"Activation-failure measurement is `{activation['measurement_status']}` because the project collects no activation telemetry. The source records the fixed issue scope and case-insensitive query expression. That review produced {len(activation['candidate_issue_numbers'])} candidates, issues {activation['candidate_issue_numbers'][0]} and {activation['candidate_issue_numbers'][1]}, but both concerned unrelated product behavior. The resulting public-issue proxy is {activation['public_issue_proxy_count']}; that does not mean zero activation failures.",
            "",
            f"The issue tracker baseline is {issues['total']} issues: {issues['open']} open and {issues['closed']} closed, excluding pull requests. It measures tracker activity rather than activation success.",
            "",
            "## External adopters",
            "",
            f"Confirmed, permissioned external adopters: **{adopters['confirmed_count']}**. One external evaluator reported a real-PDF table workflow in [issue {adopters['evaluator_issue_number']}]({adopters['evaluator_issue_url']}), but did not confirm current success or production use and is not counted as a confirmed adopter. Public dependent repositories are kept separate for the same reason.",
            "",
            "## Growth-target status",
            "",
            f"No quarterly growth target is defined. {targets['reason']}",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the rendered page is stale")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        data = load_source()
        validate(data)
        output = REPO_ROOT / str(data["output_path"])
        rendered = render(data)
        if args.check:
            if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
                print(f"adoption baseline is stale: {output.relative_to(REPO_ROOT)}", file=sys.stderr)
                return 1
            print(f"adoption baseline is current: {output.relative_to(REPO_ROOT)}")
            return 0
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")
        print(f"wrote {output.relative_to(REPO_ROOT)}")
        return 0
    except BaselineError as error:
        print(f"adoption baseline error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
