#!/usr/bin/env python3
"""Regenerate the hash-pinned reference lock file (PARITY-001, PARITY-030).

A lock file nobody can regenerate becomes unmaintainable the first time the
target moves, so the lock is produced by this script rather than by hand.

    python3 scripts/lock_golden_env.py            # rewrite the lock file
    python3 scripts/lock_golden_env.py --check    # fail if it is out of date

Resolution comes from pip; hashes come from the PyPI JSON API. Every published
file for a resolved version is recorded, not just the wheel that matches this
machine, so one lock file installs on every supported platform.

Requires network access. Run it only when deliberately changing the pinned
environment, and review the resulting diff — it is the definition of what every
compatibility claim was measured against.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

REPO_ROOT: Path = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from compat.harness import lockfile, upstream  # noqa: E402

PYPI_JSON_URL: str = "https://pypi.org/pypi/{name}/{version}/json"
NETWORK_TIMEOUT_SECONDS: int = 60

# `extra == "..."` requirements belong to optional features nothing here installs.
_EXTRA_MARKER = re.compile(r"\bextra\s*==")
_DEPENDENCY = re.compile(
    r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)"
    r"(?:\s*\[[^\]]*\])?"
    r"\s*(?P<specifier>[^;]*)"
    r"(?:;\s*(?P<marker>.+))?$"
)

HEADER: str = """\
# Pinned reference environment for Python pdfplumber compatibility testing.
#
# Generated by scripts/lock_golden_env.py -- do not edit by hand.
# Regenerate with:
#
#     python3 scripts/lock_golden_env.py
#
# Every requirement is pinned with `==` and carries the SHA-256 of every file
# published for that version, so `pip install --require-hashes` rebuilds the
# same environment on every supported platform. The target itself is declared
# in compat/upstream.toml; changing it is a target upgrade, not a refresh.
"""


def _pip_resolve(requirement: str) -> list[dict]:
    """Resolve `requirement` and its dependencies without installing anything."""
    with tempfile.TemporaryDirectory() as directory:
        report_path: Path = Path(directory) / "report.json"
        subprocess.run(
            [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--dry-run",
                "--ignore-installed",
                "--quiet",
                "--report",
                str(report_path),
                requirement,
            ],
            check=True,
        )
        report: dict = json.loads(report_path.read_text())
    return [entry["metadata"] for entry in report["install"]]


def _dependency_edges(metadata: dict) -> list[tuple[str, str, str]]:
    """(name, specifier, marker) for each non-optional dependency."""
    edges: list[tuple[str, str, str]] = []
    for raw in metadata.get("requires_dist") or []:
        if _EXTRA_MARKER.search(raw):
            continue
        matched = _DEPENDENCY.match(raw.strip())
        if matched is None:
            raise ValueError(f"cannot parse dependency {raw!r} of {metadata['name']}")
        edges.append(
            (
                matched.group("name"),
                (matched.group("specifier") or "").strip(),
                (matched.group("marker") or "").strip().replace("'", '"'),
            )
        )
    return edges


def _conjoin(left: str, right: str) -> str:
    """Marker conjunction, where an empty marker means "always applies"."""
    if not left:
        return right
    if not right:
        return left
    return f"({left}) and ({right})"


def _disjoin(left: str, right: str) -> str:
    """Marker disjunction; reachable unconditionally by any route wins."""
    if not left or not right:
        return ""
    if left == right:
        return left
    return f"({left}) or ({right})"


def _effective_markers(root: str, edges: dict[str, list[tuple[str, str]]]) -> dict[str, str]:
    """Under which conditions each package is actually installed.

    A package inherits the marker of the edge that reaches it, conjoined with
    whatever guards its parent. `cffi` is a concrete case: pip resolves it
    unconditionally on CPython, but upstream only requires it when the
    interpreter is not PyPy, and the lock must say so.
    """
    markers: dict[str, str] = {root: ""}
    changed: bool = True
    while changed:
        changed = False
        for parent, children in edges.items():
            if parent not in markers:
                continue
            for child, edge_marker in children:
                reachable: str = _conjoin(markers[parent], edge_marker)
                combined: str = (
                    _disjoin(markers[child], reachable) if child in markers else reachable
                )
                if markers.get(child) != combined:
                    markers[child] = combined
                    changed = True
    return markers


def _resolve_closure(root_requirement: str) -> dict[str, dict[str, str]]:
    """Resolve the full dependency closure, including marker-gated branches.

    pip evaluates markers against the interpreter running it, so a dependency
    guarded by `python_full_version < "3.11"` is simply absent from the report
    on a newer Python. Those edges are resolved separately, so the lock file
    also installs on the oldest supported interpreter.
    """
    versions: dict[str, dict[str, str]] = {}
    edges: dict[str, list[tuple[str, str]]] = {}
    pending: list[str] = [root_requirement]
    root: str = ""

    while pending:
        requirement: str = pending.pop(0)
        for metadata in _pip_resolve(requirement):
            canonical: str = lockfile.canonicalize(metadata["name"])
            if not root:
                root = canonical
            if canonical in versions:
                continue
            versions[canonical] = {"name": metadata["name"], "version": metadata["version"]}
            edges[canonical] = []
            for name, specifier, marker in _dependency_edges(metadata):
                edges[canonical].append((lockfile.canonicalize(name), marker))
                if marker and lockfile.canonicalize(name) not in versions:
                    print(f"resolving marker-gated dependency: {name}{specifier} ; {marker}")
                    pending.append(f"{name}{specifier}")

    markers: dict[str, str] = _effective_markers(root, edges)
    return {
        canonical: {**entry, "marker": markers.get(canonical, "")}
        for canonical, entry in versions.items()
    }


def _published_hashes(name: str, version: str) -> list[str]:
    url: str = PYPI_JSON_URL.format(name=name, version=version)
    with urllib.request.urlopen(url, timeout=NETWORK_TIMEOUT_SECONDS) as response:
        payload: dict = json.loads(response.read())
    digests: list[str] = sorted(entry["digests"]["sha256"] for entry in payload["urls"])
    if not digests:
        raise ValueError(f"PyPI lists no files for {name}=={version}")
    return digests


def render(locked: dict[str, dict[str, str]]) -> str:
    lines: list[str] = [HEADER]
    for canonical in sorted(locked):
        entry: dict[str, str] = locked[canonical]
        print(f"fetching hashes: {entry['name']}=={entry['version']}")
        digests: list[str] = _published_hashes(entry["name"], entry["version"])
        specifier: str = f"{entry['name']}=={entry['version']}"
        if entry["marker"]:
            specifier += f" ; {entry['marker']}"
        continuations: list[str] = [f"    --hash=sha256:{digest}" for digest in digests]
        lines.append(" \\\n".join([specifier, *continuations]))
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the committed lock file differs from a fresh resolve",
    )
    arguments = parser.parse_args()

    target: upstream.Target = upstream.load_target()
    destination: Path = upstream.load_environment().lockfile
    print(f"locking {target.project}=={target.version}")

    rendered: str = render(_resolve_closure(f"{target.project}=={target.version}"))

    if arguments.check:
        current: str = destination.read_text() if destination.exists() else ""
        if current != rendered:
            print(f"{destination} is out of date; rerun scripts/lock_golden_env.py")
            return 1
        print(f"{destination} is up to date")
        return 0

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(rendered)
    print(f"wrote {destination}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
