"""Contracts for the versioned, generated public readiness page."""

from __future__ import annotations

import subprocess
import sys
import unittest
from pathlib import Path

import tomllib

REPO_ROOT = Path(__file__).resolve().parents[2]
SOURCE_PATH = REPO_ROOT / "readiness.toml"
GENERATOR_PATH = REPO_ROOT / "scripts" / "generate_readiness.py"
SOURCE = tomllib.loads(SOURCE_PATH.read_text(encoding="utf-8"))
RELEASE_VERSION = SOURCE["release_version"]
OUTPUT_PATH = REPO_ROOT / "docs" / "readiness" / f"v{RELEASE_VERSION}.md"


class ReadinessPageContractTests(unittest.TestCase):
    def test_readme_links_to_the_versioned_readiness_page(self) -> None:
        readme = (REPO_ROOT / "README.md").read_text(encoding="utf-8")

        self.assertIn(f"(docs/readiness/v{RELEASE_VERSION}.md)", readme)

    def test_source_generator_and_versioned_output_exist(self) -> None:
        for path in (SOURCE_PATH, GENERATOR_PATH, OUTPUT_PATH):
            with self.subTest(path=path.relative_to(REPO_ROOT)):
                self.assertTrue(path.is_file())

    def test_ci_rejects_readiness_drift(self) -> None:
        ci = (REPO_ROOT / ".github" / "workflows" / "ci.yml").read_text(
            encoding="utf-8"
        )

        self.assertIn("python scripts/generate_readiness.py --check", ci)

    def test_generated_page_is_current_and_evidence_backed(self) -> None:
        required_paths = (SOURCE_PATH, GENERATOR_PATH, OUTPUT_PATH)
        missing = False
        for path in required_paths:
            with self.subTest(path=path.relative_to(REPO_ROOT)):
                exists = path.is_file()
                self.assertTrue(exists)
                missing |= not exists
        if missing:
            return

        completed = subprocess.run(
            [sys.executable, str(GENERATOR_PATH), "--check"],
            cwd=REPO_ROOT,
            check=False,
            capture_output=True,
            text=True,
        )
        self.assertEqual(
            completed.returncode,
            0,
            f"{completed.stdout}{completed.stderr}",
        )

        source = tomllib.loads(SOURCE_PATH.read_text(encoding="utf-8"))
        self.assertEqual(source["schema_version"], 1)
        self.assertEqual(source["release_version"], RELEASE_VERSION)
        self.assertEqual(
            [workflow["id"] for workflow in source["workflows"]],
            ["rust", "python", "cli", "wasm"],
        )
        for workflow in source["workflows"]:
            with self.subTest(workflow=workflow["id"]):
                self.assertTrue(workflow["task_ids"])
                self.assertTrue(workflow["test_ids"])
                self.assertNotIn("status", workflow)

        output = OUTPUT_PATH.read_text(encoding="utf-8")
        for phrase in (
            f"# What is ready today? — v{RELEASE_VERSION}",
            "Generated by `scripts/generate_readiness.py`",
            "## Ready workflows",
            "## Milestone state",
            "CI-contracted",
            "support-matrix.toml",
            "PRD.md",
            "readiness.toml",
        ):
            with self.subTest(phrase=phrase):
                self.assertIn(phrase, output)
        for milestone_id in ("M0", "M1", "M2", "M3", "M4"):
            with self.subTest(milestone=milestone_id):
                self.assertIn(f"| {milestone_id} |", output)


if __name__ == "__main__":
    unittest.main()
